
subjects:
  - name: alice
    token: "PASTE_ALICE_JWT_HERE"
    claims: { sub: "alice-id", roles: ["user"], tenant: "t1" }
  - name: bob
    token: "PASTE_BOB_JWT_HERE"
    claims: { sub: "bob-id", roles: ["user"], tenant: "t2" }

# Adjust paths to your crAPI version (see HAR)
invariants:
  - name: "User can only read own profile"
    when: { method: GET, path: "/identity/api/v2/user/{id}" }
    allow_if: "subject.claims.sub == path.id or 'admin' in subject.claims.roles"

  - name: "User can only read own vehicles"
    when: { method: GET, path: "/community/api/v2/user/{id}/vehicles" }
    allow_if: "subject.claims.sub == path.id or 'admin' in subject.claims.roles"
