
subjects:
  - name: alice
    token: "alice-token"
    claims: { sub: "u1", roles: ["user"], tenant: "t1" }
  - name: bob
    token: "bob-token"
    claims: { sub: "u2", roles: ["user"], tenant: "t2" }

invariants:
  - name: "Self-only profile read"
    when: { method: GET, path: "/users/{id}" }
    allow_if: "subject.claims.sub == path.id"
