
openapi: 3.0.0
info:
  title: Mock API with BOLA
  version: "1.0.0"
paths:
  /users/{id}:
    get:
      summary: Get user by id
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        "200": { description: OK }
        "401": { description: Unauthorized }
        "404": { description: Not Found }
