
name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install -r requirements.txt
          pip install pytest
      - name: Unit tests
        run: |
          pytest -q
      - name: Start mock API
        run: |
          nohup uvicorn examples.mock_api.server:app --host 127.0.0.1 --port 8000 &
          sleep 2
      - name: Run AuthScope on mock
        run: |
          authscope run --base http://127.0.0.1:8000             --openapi examples/mock_api/openapi.yaml             --config examples/mock_api/config.yaml             --out out
      - name: Archive report
        uses: actions/upload-artifact@v4
        with:
          name: authscope-report
          path: out/
